---
- hosts: all
  vars:
    mysql_root_password: password
  tasks:
    - name: Install MySQL
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      sudo: yes
      with_items:
        - python-mysqldb
        - mysql-server
    - name: Start the MySQL service
      sudo: yes
      service:
        name: mysql
        state: started
        enabled: true
    - name: Import TFG_DB
      shell: mysql -u root -ppassword db_name < /home/ubuntu/sql_files/tfg.sql
