- hosts: all
  user: ubuntu
  sudo: true

  tasks:
    - name: Install MySQL
      apt:
        name: "{{ item }}"
      with_items:
        - python-mysqldb
        - mysql-server
        - mysql-client

    - name: Start the MySQL service
      action: service name=mysql state=started

    - name: Update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "password"
        priv: "*.*:ALL,GRANT"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Remove the test database
      mysql_db: name=test state=absent

    - name: Import file.sql
      mysql_db:
        login_user: root
        login_password: root
        state: import
        name: all
        target: /home/ubuntu/sql_files/tfg.sql
